#!/usr/bin/env python3
"""
Stumble Bot - Game Automation Tool
Main entry point for the application.

A modular bot for game automation using computer vision and virtual Xbox controller.
Features:
- Visual template detection using OpenCV
- Virtual Xbox 360 controller simulation
- Window management and focus control
- GUI interface with configuration management
- Manual controller interface

Author: Generated by GitHub Copilot
Version: 1.0.0
"""

import sys
import os
import traceback
import logging
from pathlib import Path

# Add the current directory to Python path to ensure module imports work
current_dir = Path(__file__).parent
sys.path.insert(0, str(current_dir))

try:
    from app import StumbleBotApp
except ImportError as e:
    print(f"Error importing application: {e}")
    print("Make sure all required packages are installed:")
    print("pip install -r requirements.txt")
    sys.exit(1)


def setup_logging():
    """Setup logging configuration."""
    # Create logs directory if it doesn't exist
    logs_dir = current_dir / "logs"
    logs_dir.mkdir(exist_ok=True)
    
    # Configure logging
    log_file = logs_dir / "stumble_bot.log"
    
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler(log_file),
            logging.StreamHandler(sys.stdout)
        ]
    )
    
    return logging.getLogger("StumbleBot")


def check_dependencies():
    """Check if all required dependencies are available."""
    required_packages = [
        'customtkinter',
        'cv2',
        'numpy',
        'vgamepad',
        'pygetwindow',
        'PIL',
        'win32gui'
    ]
    
    missing_packages = []
    
    for package in required_packages:
        try:
            if package == 'cv2':
                import cv2
            elif package == 'PIL':
                from PIL import Image
            elif package == 'win32gui':
                import win32gui
            else:
                __import__(package)
        except ImportError:
            missing_packages.append(package)
    
    if missing_packages:
        print("Missing required packages:")
        for package in missing_packages:
            print(f"  - {package}")
        print("\nPlease install missing packages:")
        print("pip install -r requirements.txt")
        return False
    
    return True


def check_system_requirements():
    """Check system requirements."""
    logger = logging.getLogger("StumbleBot")
    
    # Check operating system
    if not sys.platform.startswith('win'):
        logger.warning("This application is designed for Windows. Some features may not work on other platforms.")
    
    # Check Python version
    if sys.version_info < (3, 7):
        logger.error("Python 3.7 or higher is required.")
        return False
    
    logger.info(f"Python version: {sys.version}")
    logger.info(f"Platform: {sys.platform}")
    
    return True


def create_directory_structure():
    """Create necessary directory structure."""
    directories = ['templates', 'configs', 'logs']
    
    for directory in directories:
        dir_path = current_dir / directory
        dir_path.mkdir(exist_ok=True)


def main():
    """Main entry point."""
    # Setup logging
    logger = setup_logging()
    logger.info("=" * 50)
    logger.info("Starting Stumble Bot Application")
    logger.info("=" * 50)
    
    try:
        # Check system requirements
        if not check_system_requirements():
            logger.error("System requirements not met. Exiting.")
            return 1
        
        # Check dependencies
        if not check_dependencies():
            logger.error("Missing dependencies. Please install required packages.")
            return 1
        
        # Create directory structure
        create_directory_structure()
        logger.info("Directory structure verified")
        
        # Initialize and run application
        logger.info("Initializing application...")
        app = StumbleBotApp()
        
        logger.info("Starting GUI...")
        app.run()
        
        logger.info("Application closed normally")
        return 0
        
    except KeyboardInterrupt:
        logger.info("Application interrupted by user")
        return 0
        
    except Exception as e:
        logger.error(f"Unhandled exception: {e}")
        logger.error("Traceback:")
        logger.error(traceback.format_exc())
        
        # Show error dialog if possible
        try:
            import tkinter as tk
            from tkinter import messagebox
            
            root = tk.Tk()
            root.withdraw()  # Hide main window
            
            messagebox.showerror(
                "Stumble Bot Error",
                f"An unexpected error occurred:\n\n{e}\n\n"
                f"Check the log file for more details:\n{current_dir / 'logs' / 'stumble_bot.log'}"
            )
            
        except:
            pass  # If we can't show GUI error, just continue
        
        return 1


if __name__ == "__main__":
    exit_code = main()
    sys.exit(exit_code)